### PR TITLE
Add the Streets map

### PR DESCRIPTION
**Pull request by valbrimi**

### CODE REVIEW

**Comment by LambdAurora** [comment]
Why was this closed?
I didn't had time to review it at the moment but I meant to.

**Comment by komerish** [comment]
i forgot to set the bounds, i’ll do it in a few hours so you can review it

**Comment by LambdAurora** [comment]
Marking a PR as draft is better for this kind of things :p

**Comment by komerish** [comment]
fixed

**Comment by whoy51** [comment]
I love this map. Very well built. Everything looks setup properly

**Review by Gegy — APPROVED** [review]

**Pull request merged**
